version: '3'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5000:5000"
    networks:
      net:
        ipv4_address: 193.168.1.20

  retrocrypto:
    build:
      context: ./retrocrypto
    ports:
      - "4000:4000"
    networks:
      net:
        ipv4_address: 193.168.1.30

  selftrack:
    build:
      context: ./selftrack
    ports:
      - "7000:7000"
    networks:
      net:
        ipv4_address: 193.168.1.40

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      net:
        ipv4_address: 193.168.1.10

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 193.168.1.0/24

