version: '3'

networks:
  portfolio_net:
    ipam:
      config:
        - subnet: 172.168.0.0/24

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    networks:
      portfolio_net:
        ipv4_address: 172.168.0.10

  retrocrypto:
    build:
      context: ./retrocrypto
    ports:
      - "4000:4000"
    networks:
      portfolio_net:
        ipv4_address: 172.168.0.20


  ytbmp3:
    build:
      context: ./ytbmp3
    ports:
      - "3000:3000"
    networks:
      portfolio_net:
        ipv4_address: 172.168.0.30
