version: '3'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"

  retrocrypto:
    build:
      context: ./retrocrypto
    ports:
      - "4000:4000"

  ytbmp3:
    build:
      context: ./ytbmp3
    ports:
      - "3000:3000"
